"""
Feature information for MIMIC-IV

Contains:
    - ALL_COLUMNS: All features contained in the data
    - DEMOGRAPHICS: Demographic information
    - VITALS: Continuously measured vitals signs
    - LABS: Laboratory values
    - OTHER: Information that is neither a demographic, vital sign, or lab measurement. An example would be patient
        in-time to ICU.

For DEMOGRAPHICS, VITALS, LABS, OTHER, commented values are not used in the models.
"""
ALL_COLUMNS = [
    "subject_id",
    "hadm_id",
    "stay_id",
    "gender",
    "dod",
    "admittime",
    "dischtime",
    "los_hospital",
    "admission_age",
    "ethnicity",
    "hospital_expire_flag",
    "hospstay_seq",
    "first_hosp_stay",
    "icu_intime",
    "icu_outtime",
    "los_icu",
    "icustay_seq",
    "first_icu_stay",
    "height",
    "weight",
    "t_suspicion",
    "t_sofa",
    "t_sepsis_min",
    "charttime",
    "heart_rate",
    "sbp",
    "dbp",
    "mbp",
    "sbp_ni",
    "dbp_ni",
    "mbp_ni",
    "resp_rate",
    "temperature",
    "temperature_site",
    "spo2",
    "glucose",
    "respiratory_rate_set",
    "respiratory_rate_total",
    "respiratory_rate_spontaneous",
    "minute_volume",
    "tidal_volume_set",
    "tidal_volume_observed",
    "tidal_volume_spontaneous",
    "plateau_pressure",
    "peep",
    "fio2",
    "ventilator_mode",
    "ventilator_mode_hamilton",
    "ventilator_type",
    "specimen",
    "specimen_pred",
    "specimen_prob",
    "so2",
    "po2",
    "pco2",
    "fio2_labs",
    "aado2",
    "aado2_calc",
    "pao2fio2ratio",
    "ph",
    "baseexcess",
    "bicarbonate_bg",
    "totalco2",
    "hematocrit_bg",
    "hemoglobin_bg",
    "carboxyhemoglobin",
    "methemoglobin",
    "chloride_bg",
    "calcium_bg",
    "temperature_labs",
    "potassium_bg",
    "sodium_bg",
    "lactate",
    "glucose_bg",
    "wbc",
    "basophils_abs",
    "eosinophils_abs",
    "lymphocytes_abs",
    "monocytes_abs",
    "neutrophils_abs",
    "basophils",
    "eosinophils",
    "lymphocytes",
    "monocytes",
    "neutrophils",
    "atypical_lymphocytes",
    "bands",
    "immature_granulocytes",
    "metamyelocytes",
    "nrbc",
    "troponin_i",
    "troponin_t",
    "alt",
    "alp",
    "ast",
    "amylase",
    "bilirubin_total",
    "bilirubin_direct",
    "bilirubin_indirect",
    "ck_cpk",
    "ck_mb",
    "ggt",
    "ld_ldh",
    "albumin",
    "globulin",
    "total_protein",
    "aniongap",
    "bicarbonate",
    "bun",
    "calcium",
    "chloride",
    "creatinine",
    "glucose_labs",
    "sodium",
    "potassium",
    "d_dimer",
    "fibrinogen",
    "thrombin",
    "inr",
    "pt",
    "ptt",
    "hematocrit",
    "hemoglobin",
    "mch",
    "mchc",
    "mcv",
    "platelet",
    "rbc",
    "rdw",
    "rdwsd",
    "ventilation_status",
    "o2_flow",
    "o2_delivery_device",
]

DEMOGRAPHICS = ["gender", "admission_age", "ethnicity", "height", "weight"]

OTHER = [
    # "subject_id",
    # "hadm_id",
    "stay_id",
    "dod",
    "admittime",
    "dischtime",
    "los_hospital",
    "hospital_expire_flag",
    # "hospstay_seq",
    # "first_hosp_stay",
    "icu_intime",
    "icu_outtime",
    "los_icu",
    # "icustay_seq",
    # "first_icu_stay",
    "t_suspicion",
    "t_sofa",
    "t_sepsis_min",
    "charttime",
    "ventilation_status",
    # "ventilator_mode",
    # "ventilator_mode_hamilton",
    # "ventilator_type",
]

VITALS = [
    "dbp",
    "dbp_ni",
    "heart_rate",
    "mbp",
    "mbp_ni",
    # "o2_delivery_device",
    "o2_flow",
    "resp_rate",
    # "respiratory_rate_set",
    # "respiratory_rate_spontaneous",
    # "respiratory_rate_total",
    "sbp",
    # "sbp_ni",
    "spo2",
    "temperature",
    # "temperature_site",
    # "tidal_volume_observed",
    # "tidal_volume_set",
    # "tidal_volume_spontaneous",
]

LABS = [
    # "aado2",
    # "aado2_calc",
    # "albumin",
    "alp",
    # "alt",
    # "amylase",
    # "aniongap",
    "ast",
    # "atypical_lymphocytes",
    # "bands",
    "baseexcess",
    # "basophils",
    # "basophils_abs",
    # "bicarbonate",
    "bicarbonate_bg",
    "bilirubin_direct",
    # "bilirubin_indirect",
    "bilirubin_total",
    "bun",
    "calcium",
    # "calcium_bg",
    # "carboxyhemoglobin",
    "chloride",
    # "chloride_bg",
    # "ck_cpk",
    # "ck_mb",
    "creatinine",
    # "d_dimer",
    # "eosinophils",
    # "eosinophils_abs",
    "fibrinogen",
    "fio2",
    # "fio2_labs",
    # "ggt",
    # "globulin",
    "glucose",
    "glucose_bg",
    # "glucose_labs",
    "hematocrit",
    # "hematocrit_bg",
    "hemoglobin",
    # "hemoglobin_bg",
    # "immature_granulocytes",
    # "inr",
    "lactate",
    # "ld_ldh",
    # "lymphocytes",
    # "lymphocytes_abs",
    # "mch",
    # "mchc",
    # "mcv",
    # "metamyelocytes",
    # "methemoglobin",
    # "minute_volume",
    # "monocytes",
    # "monocytes_abs",
    # "neutrophils",
    # "neutrophils_abs",
    # "nrbc",
    # "pao2fio2ratio",
    "pco2",
    # "peep",
    "ph",
    # "plateau_pressure",
    "platelet",
    "po2",
    # "potassium",
    "potassium_bg",
    # "pt",
    "ptt",
    # "rbc",
    # "rdw",
    # "rdwsd",
    "so2",
    "sodium",
    # "sodium_bg",
    # "specimen",
    # "specimen_pred",
    # "specimen_prob",
    # "temperature_labs",
    # "thrombin",
    # "total_protein",
    # "totalco2",
    "troponin_i",
    # "troponin_t",
    "wbc",
]

# Note this will need additional work to handle the 'OTHER' variables into usable things
#
USE_FEATURES = OTHER + DEMOGRAPHICS + VITALS + LABS
